CREATE DATABASE e_commerce_project;
USE e_commerce_project;
CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR (255) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE products (
id INT NOT NULL AUTO_INCREMENT,
product_name VARCHAR (255) NOT NULL,
amount DECIMAL(10, 2) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE orders (
id INT NOT NULL AUTO_INCREMENT,
user_id INT NOT NULL,
product_id INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (ID),
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);